from .classification import Classification
from .face_detection import FaceDetection
from .objectDetection import ObjectDetection
from .instance_segmentation import InstanceSegmentation
from .semantic_segmentation import SemanticSegmentation